include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    constant_identifier_names: false
    join_return_with_assignment: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    library_private_types_in_public_api: false
    sort_pub_dependencies: false
